# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish
on: 
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - run: npm publish
      - name: Create Release Archives
        run: |
          # Create tarball for Unix systems
          tar -czvf ${{ github.ref_name }}.tar.gz -C .

          # Create zip for Windows users
          zip -r ${{ github.ref_name }}.zip ./
      - name: Generate Checksums
        run: |
          sha256sum ${{ github.ref_name }}.tar.gz ${{ github.ref_name }}.zip > checksums.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.ref_name }}.tar.gz,${{ github.ref_name }}.zip,checksums.txt"
